entrypoint: bundle exec rackup --port $PORT
env: flex
runtime: ruby

env_variables:
  SECRET_KEY_BASE: SECRET_KEY_BASE

beta_settings:
  cloud_sql_instances: phrasal-waters-337113:us-central1:rails-cloudsql-instance
